### ISSUE TITLE
Broken link in installation steps

### ISSUE THREAD

**Issue by WoBuGs** [CompassSecurity/BloodHoundQueries#16]
The link in [BloodHound_Custom_Queries/README.md](https://github.com/CompassSecurity/BloodHoundQueries/blob/master/BloodHound_Custom_Queries/README.md ) is broken.

The old one was: 

```
https://raw.githubusercontent.com/CompassSecurity/BloodHoundQueries/master/customqueries.json
```

It should now be: 

```
https://raw.githubusercontent.com/CompassSecurity/BloodHoundQueries/master/BloodHound_Custom_Queries/customqueries.json
```

**Comment by emanuelduss** [comment]
Hi WoBuGs

Thanks!

I corrected the link in https://github.com/CompassSecurity/BloodHoundQueries/commit/317ac16747b7d76f90a1e8d1240e07d18593b452.

Best,
Emanuel
