### ISSUE TITLE
Cypher "toint" error

### ISSUE THREAD

**Issue by 0xvm** [CompassSecurity/BloodHoundQueries#3]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8582187/119226302-17056600-bb11-11eb-9c9a-e729fc88a219.png">

toint errors out in recent cypher versions since deprecated.

Perhaps we can replace it with toInteger which works fine?  If you would like i can submit a PR.

**Comment by sploutchy** [comment]
Thanks for the issue, this is now fixed.
Cheers
